<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('productos')->insert([
            // Hamburguesas (categoria_id: 1)
            [
                'nombre' => 'Clásica Umami',
                'descripcion' => 'Preparada con gírgolas frescas, pan artesanal y condimentos naturales. La versión más equilibrada y sabrosa de una burger plant-based.',
                'precio' => 7000,
                'stock' => 25,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-clasica-umami-productos.webp',
                'etiqueta' => 'Clásico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mediterránea',
                'descripcion' => 'Inspirada en sabores del Mediterráneo, con tomate seco, aceitunas y especias naturales. Fresca, aromática y ligera.',
                'precio' => 9200,
                'stock' => 20,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-mediterranea-umami-productos.webp',
                'etiqueta' => 'Mediterránea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Fungi BBQ',
                'descripcion' => 'Hongos a la parrilla con salsa barbacoa artesanal. Textura jugosa y sabor ahumado que conquista.',
                'precio' => 9000,
                'stock' => 18,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-fungi-bbq-umami-productos.webp',
                'etiqueta' => 'BBQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Spicy Gírgola',
                'descripcion' => 'Gírgolas marinadas en especias picantes y toque ahumado. Energética, audaz y sabrosa.',
                'precio' => 9500,
                'stock' => 22,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-spicy-girgola-umami-productos.webp',
                'etiqueta' => 'Picante',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Trufa & Shiitake',
                'descripcion' => 'Shiitakes salteados y aceite de trufa negra. Una experiencia gourmet intensa y sofisticada.',
                'precio' => 9.800,
                'stock' => 15,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-trufa-shiitake-umami-productos.webp',
                'etiqueta' => 'Gourmet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Umami Oriental',
                'descripcion' => 'Gírgolas salteadas con salsa miso y jengibre, cebolla caramelizada, pickles de pepino y una mayonesa umami con toque de sésamo; textura jugosa y perfil claramente oriental pero 100% plant-based.',
                'precio' => 9800,
                'stock' => 20,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-umami-oriental-umami-productos.webp',
                'etiqueta' => 'Oriental',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Andina Gluten Free',
                'descripcion' => 'Medallón de hongos y lentejas, pan de quinoa sin gluten, palta fresca y brotes. Una opción nutritiva y libre de gluten.',
                'precio' => 8500,
                'stock' => 50,
                'categoria_id' => 1,
                'imagen' => 'andina-gluten-free-umami-productos.webp',
                'etiqueta' => 'Gluten Free',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Tex Mex Veggie',
                'descripcion' => 'Portobello especiado, guacamole, maíz asado, pico de gallo y nachos crocantes. Sabores intensos y vibrantes.',
                'precio' => 9200,
                'stock' => 60,
                'categoria_id' => 1,
                'imagen' => 'tex-mex-veggie-umami-productos.webp',
                'etiqueta' => 'Tex Mex',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Wraps (categoria_id: 2)
            [
                'nombre' => 'Wrap de Hongos',
                'descripcion' => 'Mix de hongos, vegetales y aderezo de limón y sésamo envueltos en pan integral. Ligero y nutritivo.',
                'precio' => 6500,
                'stock' => 25,
                'categoria_id' => 2,
                'imagen' => 'wrap-de-hongos-umami-productos.webp',
                'etiqueta' => 'Saludable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // acompañamientos (categoria_id: 3)
            [
                'nombre' => 'Combo Papas + Salsa Especial',
                'descripcion' => 'Porción grande de papas rústicas cortadas a mano servidas con nuestra Salsa Especial UMAMI (base cremosa, ajo rostizado, reducción de miso y toque cítrico). Perfecto para compartir o como acompañamiento premium.',
                'precio' => 4200,
                'stock' => 100,
                'categoria_id' => 3,
                'imagen' => 'combo-papas-salsaUmami-umami-productos.webp',
                'etiqueta' => 'Combo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Rústicas',
                'descripcion' => 'Cortadas a mano, cocidas al horno y sazonadas con sal UMAMI. Crocantes por fuera, suaves por dentro.',
                'precio' => 3500,
                'stock' => 40,
                'categoria_id' => 3,
                'imagen' => 'papas-rusticas-umami-productos.webp',
                'etiqueta' => 'Clásico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Bastones de Shiitake Crocantes',
                'descripcion' => 'Shiitakes empanizados y crocantes. Perfectos para acompañar o picar solo.',
                'precio' => 4500,
                'stock' => 30,
                'categoria_id' => 3,
                'imagen' => 'bastones-shiitake-umami-productos.webp',
                'etiqueta' => 'Crocante',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //condimentos (categoria_id: 4)
            [
                'nombre' => 'Sal umami',
                'descripcion' => 'Mezcla artesanal de sales marinas y hongos deshidratados. Potencia cualquier plato naturalmente.',
                'precio' => 2500,
                'stock' => 50,
                'categoria_id' => 4,
                'imagen' => 'sal-umami-productos.webp',
                'etiqueta' => 'Natural',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bebidas (categoria_id: 5)
            [
                'nombre' => 'Limonada umami',
                'descripcion' => 'Refrescante, casera y herbal. Ideal para equilibrar sabores intensos.',
                'precio' => 4800,
                'stock' => 45,
                'categoria_id' => 5,
                'imagen' => 'limonada-umami-productos.webp',
                'etiqueta' => 'Natural',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Agua Reishi',
                'descripcion' => 'Agua funcional con extracto de Reishi, antioxidante y relajante.',
                'precio' => 5000,
                'stock' => 40,
                'categoria_id' => 5,
                'imagen' => 'agua-reishi-umami-productos.webp',
                'etiqueta' => 'Funcional',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Agua Maitake',
                'descripcion' => 'Bebida infusionada con Maitake, ideal para fortalecer el sistema inmune.',
                'precio' => 5000,
                'stock' => 40,
                'categoria_id' => 5,
                'imagen' => 'agua-maitake-umami-productos.webp',
                'etiqueta' => 'Funcional',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cerveza Artesanal Umami',
                'descripcion' => 'Cerveza ligera y fresca que complementa perfectamente los sabores de hongos.',
                'precio' => 6800,
                'stock' => 25,
                'categoria_id' => 5,
                'imagen' => 'cerveza-umami-productos.webp',
                'etiqueta' => 'Artesanal',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //postres (categoria_id: 6)
            [
                'nombre' => 'Brownie shiitake',
                'descripcion' => 'Delicioso brownie vegano con polvo de hongos adaptógenos. Dulce, saludable y nutritivo.',
                'precio' => 4500,
                'stock' => 30,
                'categoria_id' => 6,
                'imagen' => 'brownie-de-hongos-umami-productos.webp',
                'etiqueta' => 'vegano',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cheesecake de anacardos y reishi',
                'descripcion' => 'Postre cremoso y sin lácteos, infusionado con Reishi. Sabor suave y textura aterciopelada.',
                'precio' => 5200,
                'stock' => 20,
                'categoria_id' => 6,
                'imagen' => 'cheesecake-de-anacardos-y-reishi-umami-productos.webp',
                'etiqueta' => 'sin-lacteos',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Combos (categoria_id: 7)
            [
                'nombre' => 'Combo Clásico umami',
                'descripcion' => 'Hamburguesa Clásica + Papas Rústicas + Limonada UMAMI. La experiencia base de UMAMI.',
                'precio' => 11500,
                'stock' => 25,
                'categoria_id' => 7,
                'imagen' => 'combo-clasico-umami-productos.webp',
                'etiqueta' => 'Clásico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Combo Mediterráneo',
                'descripcion' => 'Hamburguesa Mediterránea + Papas especiadas + Agua Reishi. Ligero y fresco.',
                'precio' => 12800,
                'stock' => 20,
                'categoria_id' => 7,
                'imagen' => 'combo-mediterraneo-umami-productos.webp',
                'etiqueta' => 'Mediterráneo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Combo Fungi BBQ',
                'descripcion' => 'Hamburguesa Fungi BBQ + Papas & Salsas + Bebida línea Coca-Cola. Intenso y ahumado.',
                'precio' => 12600,
                'stock' => 22,
                'categoria_id' => 7,
                'imagen' => 'combo-fungi-bbq-umami-productos.webp',
                'etiqueta' => 'BBQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Combo Trufa & Shiitake',
                'descripcion' => 'Hamburguesa Trufa & Shiitake + Bastones Crocantes + Agua Maitake. Gourmet y sofisticado.',
                'precio' => 13900,
                'stock' => 18,
                'categoria_id' => 7,
                'imagen' => 'combo-trufa-shiitake-umami-productos.webp',
                'etiqueta' => 'Gourmet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Combo Spicy Gírgola',
                'descripcion' => 'Hamburguesa Spicy Gírgola + Bastones Crocantes + Limonada UMAMI. Picante y energético.',
                'precio' => 12300,
                'stock' => 20,
                'categoria_id' => 7,
                'imagen' => 'combo-spicy-girgola-umami-productos.webp',
                'etiqueta' => 'Picante',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Combo Wrap Saludable',
                'descripcion' => 'Wrap de Hongos + Papas Rústicas + Agua Mineral. Liviano y fresco.',
                'precio' => 10900,
                'stock' => 28,
                'categoria_id' => 7,
                'imagen' => 'combo-wrap-saludable-umami-productos.webp',
                'etiqueta' => 'Saludable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Combo Nuggets Fan',
                'descripcion' => 'Nuggets de Hongos + Papas & Salsas + Limonada UMAMI. Divertido y crocante.',
                'precio' => 9800,
                'stock' => 30,
                'categoria_id' => 7,
                'imagen' => 'combo-nuggets-fan-umami-productos.webp',
                'etiqueta' => 'Familiar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Combo Dúo',
                'descripcion' => '2 Hamburguesas a elección + Papas XL + 2 bebidas. Ideal para compartir.',
                'precio' => 22500,
                'stock' => 15,
                'categoria_id' => 7,
                'imagen' => 'combo-duo-umami-productos.webp',
                'etiqueta' => 'Compartir',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Combo Wrap y Sal',
                'descripcion' => 'Wrap de Hongos + Sal UMAMI + Cerveza + Tiramisú. Completo y equilibrado.',
                'precio' => 13500,
                'stock' => 18,
                'categoria_id' => 7,
                'imagen' => 'combo-sobres-cerveza-postre-umami-productos.webp',
                'etiqueta' => 'Completo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
