<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('productos')->insert([
            // Hamburguesas (categoria_id: 1)
            [
                'producto_id' => 1,
                'nombre' => 'Clásica Umami',
                'descripcion_corta' => 'Medallón de gírgolas frescas, queso cheddar vegano, lechuga, tomate, cebolla morada y salsa especial Umami, en pan artesanal de papa.',
                'descripcion' => 'Preparada con gírgolas frescas, pan artesanal y condimentos naturales. La versión más equilibrada y sabrosa de una burger plant-based.',
                'precio' => 7000,
                'stock' => 25,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-clasica-umami-productos.webp',
                'etiqueta' => 'Clásico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 2,
                'nombre' => 'Mediterránea',
                'descripcion_corta' => 'Hongos de estación con tomates secos, espinaca fresca y aderezo de ajo confitado.',
                'descripcion' => 'Inspirada en sabores del Mediterráneo, con tomate seco, aceitunas y especias naturales. Fresca, aromática y ligera.',
                'precio' => 9200,
                'stock' => 20,
                'categoria_id' => 1,
                'imagen' => 'mediterranea-umami-productos.webp',
                'etiqueta' => 'Mediterránea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 3,
                'nombre' => 'Fungi BBQ',
                'descripcion_corta' => 'Hamburguesa de portobellos grillados con salsa barbacoa casera, cebolla caramelizada y rúcula fresca.',
                'descripcion' => 'Hongos a la parrilla con salsa barbacoa artesanal. Textura jugosa y sabor ahumado que conquista.',
                'precio' => 9000,
                'stock' => 18,
                'categoria_id' => 1,
                'imagen' => 'fungi-BBQ-umami-productos.webp',
                'etiqueta' => 'BBQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 4,
                'nombre' => 'Spicy Gírgola',
                'descripcion_corta' => 'Gírgolas crocantes con salsa picante de chipotle, jalapeños en rodajas y cebolla crispy.',
                'descripcion' => 'Gírgolas marinadas en especias picantes y toque ahumado. Energética, audaz y sabrosa.',
                'precio' => 9500,
                'stock' => 22,
                'categoria_id' => 1,
                'imagen' => 'spicy-girgola-umami-productos.webp',
                'etiqueta' => 'Picante',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 5,
                'nombre' => 'Trufa & Shiitake',
                'descripcion_corta' => 'Medallón de shiitake y gírgolas con crema suave de trufa, rúcula fresca y queso vegano fundido.',
                'descripcion' => 'Shiitakes salteados y aceite de trufa negra. Una experiencia gourmet intensa y sofisticada.',
                'precio' => 9800,
                'stock' => 15,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-trufa-shiitake-umami-productos.webp',
                'etiqueta' => 'Gourmet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 6,
                'nombre' => 'Umami Oriental',
                'descripcion_corta' => 'Hongos shiitake y portobellos, acompañada de pepino encurtido, salsa de soja dulce, jengibre fresco y mayonesa de wasabi suave en pan artesanal de sésamo.',
                'descripcion' => 'Gírgolas salteadas con salsa miso y jengibre, cebolla caramelizada, pickles de pepino y una mayonesa umami con toque de sésamo; textura jugosa y perfil claramente oriental pero 100% plant-based.',
                'precio' => 9800,
                'stock' => 20,
                'categoria_id' => 1,
                'imagen' => 'hamburguesa-umami-oriental-umami-productos.webp',
                'etiqueta' => 'Oriental',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 7,
                'nombre' => 'Andina Gluten Free',
                'descripcion_corta' => 'Medallón de hongos y lentejas, pan de quinoa sin gluten, palta fresca y brotes.',
                'descripcion' => 'Medallón de hongos y lentejas, pan de quinoa sin gluten, palta fresca y brotes. Una opción nutritiva y libre de gluten.',
                'precio' => 8500,
                'stock' => 50,
                'categoria_id' => 1,
                'imagen' => 'andina-gluten-free-umami-productos.webp',
                'etiqueta' => 'Gluten Free',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 8,
                'nombre' => 'Tex Mex Veggie',
                'descripcion_corta' => 'Portobello especiado, guacamole, maíz asado, pico de gallo y nachos crocantes.',
                'descripcion' => 'Portobello especiado, guacamole, maíz asado, pico de gallo y nachos crocantes. Sabores intensos y vibrantes.',
                'precio' => 9200,
                'stock' => 60,
                'categoria_id' => 1,
                'imagen' => 'tex-mex-veggie-umami-productos.webp',
                'etiqueta' => 'Tex Mex',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Wraps (categoria_id: 2)
            [
                'producto_id' => 9,
                'nombre' => 'Wrap de Hongos',
                'descripcion_corta' => 'Gírgolas salteadas al wok, vegetales de estación y nuestra salsa especial de hongos que realza cada bocado.',
                'descripcion' => 'Mix de hongos, vegetales y aderezo de limón y sésamo envueltos en pan integral. Ligero y nutritivo.',
                'precio' => 6500,
                'stock' => 25,
                'categoria_id' => 2,
                'imagen' => 'wrap-de-hongos-umami-productos.webp',
                'etiqueta' => 'Saludable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // acompañamientos (categoria_id: 3)
            [
                'producto_id' => 10,
                'nombre' => 'Combo Papas + Salsa Especial',
                'descripcion_corta' => 'Papas clásicas con salsa Umami de hongos y hierbas frescas.',
                'descripcion' => 'Porción grande de papas rústicas cortadas a mano servidas con nuestra Salsa Especial UMAMI (base cremosa, ajo rostizado, reducción de miso y toque cítrico). Perfecto para compartir o como acompañamiento premium.',
                'precio' => 4200,
                'stock' => 100,
                'categoria_id' => 3,
                'imagen' => 'combo-papas-salsaUmami-umami-productos.webp',
                'etiqueta' => 'Combo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 11,
                'nombre' => 'Papas Rústicas',
                'descripcion_corta' => 'Papas cortadas a mano, condimentadas con sal ahumada y romero.',
                'descripcion' => 'Cortadas a mano, cocidas al horno y sazonadas con sal UMAMI. Crocantes por fuera, suaves por dentro.',
                'precio' => 3500,
                'stock' => 40,
                'categoria_id' => 3,
                'imagen' => 'papas-rusticas-umami-productos.webp',
                'etiqueta' => 'Clásico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 12,
                'nombre' => 'Bastones de Shiitake Crocantes',
                'descripcion_corta' => 'Bastones de hongos shiitake apanados con mix de semillas, acompañados con alioli de ajo asado.',
                'descripcion' => 'Shiitakes empanizados y crocantes. Perfectos para acompañar o picar solo.',
                'precio' => 4500,
                'stock' => 30,
                'categoria_id' => 3,
                'imagen' => 'bastones-shiitake-crocantes-umami-productos.webp',
                'etiqueta' => 'Crocante',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //condimentos (categoria_id: 4)
            [
                'producto_id' => 13,
                'nombre' => 'Sal umami',
                'descripcion_corta' => 'Sal marina infusionada con hongos deshidratados, diseñada para potenciar el sabor natural de cada plato con un toque único y sofisticado.',
                'descripcion' => 'Mezcla artesanal de sales marinas y hongos deshidratados. Potencia cualquier plato naturalmente.',
                'precio' => 2500,
                'stock' => 50,
                'categoria_id' => 4,
                'imagen' => 'sal-umami-productos.webp',
                'etiqueta' => 'Natural',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bebidas (categoria_id: 5)
            [
                'producto_id' => 14,
                'nombre' => 'Limonada umami',
                'descripcion_corta' => 'Limonada fresca con un toque de jengibre y albahaca.',
                'descripcion' => 'Refrescante, casera y herbal. Ideal para equilibrar sabores intensos.',
                'precio' => 4800,
                'stock' => 45,
                'categoria_id' => 5,
                'imagen' => 'limonada-umami-umami-productos.webp',
                'etiqueta' => 'Natural',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 15,
                'nombre' => 'Agua Reishi',
                'descripcion_corta' => 'Infusión refrescante de hongos reishi con toques cítricos, energizante y natural.',
                'descripcion' => 'Agua funcional con extracto de Reishi, antioxidante y relajante.',
                'precio' => 5000,
                'stock' => 40,
                'categoria_id' => 5,
                'imagen' => 'agua-de-reishi-refrescante-umami-productos.webp',
                'etiqueta' => 'Funcional',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 16,
                'nombre' => 'Agua Maitake',
                'descripcion_corta' => 'Agua saborizada con extracto de maitake, con notas herbales y revitalizantes.',
                'descripcion' => 'Bebida infusionada con Maitake, ideal para fortalecer el sistema inmune.',
                'precio' => 5000,
                'stock' => 40,
                'categoria_id' => 5,
                'imagen' => 'agua-de-maitake-umami-productos.webp',
                'etiqueta' => 'Funcional',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 17,
                'nombre' => 'Cerveza Artesanal Umami',
                'descripcion_corta' => 'Golden ale infusionada con hongos portobello, suave y equilibrada.',
                'descripcion' => 'Cerveza ligera y fresca que complementa perfectamente los sabores de hongos.',
                'precio' => 6800,
                'stock' => 25,
                'categoria_id' => 5,
                'imagen' => 'cerveza-umami-artesanal-umami-productos.webp',
                'etiqueta' => 'Artesanal',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //postres (categoria_id: 6)
            [
                'producto_id' => 18,
                'nombre' => 'Brownie shiitake',
                'descripcion_corta' => 'Brownie húmedo con extracto de shiitake, chocolate amargo 70% y nueces.',
                'descripcion' => 'Delicioso brownie vegano con polvo de hongos adaptógenos. Dulce, saludable y nutritivo.',
                'precio' => 4500,
                'stock' => 30,
                'categoria_id' => 6,
                'imagen' => 'brownie-shiitake-umami-productos.webp',
                'etiqueta' => 'vegano',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 19,
                'nombre' => 'Cheesecake de anacardos y reishi',
                'descripcion_corta' => 'Cheesecake cremoso con base de galletas integrales y un toque de hongo reishi.',
                'descripcion' => 'Postre cremoso y sin lácteos, infusionado con Reishi. Sabor suave y textura aterciopelada.',
                'precio' => 5200,
                'stock' => 20,
                'categoria_id' => 6,
                'imagen' => 'cheesecake-reishi-umami-productos.webp',
                'etiqueta' => 'sin-lacteos',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Combos (categoria_id: 7)
            [
                'producto_id' => 20,
                'nombre' => 'Combo Clásico umami',
                'descripcion_corta' => 'Hamburguesa Clásica + Papas Rústicas + Limonada Umami.',
                'descripcion' => 'Hamburguesa Clásica + Papas Rústicas + Limonada UMAMI. La experiencia base de UMAMI.',
                'precio' => 11500,
                'stock' => 25,
                'categoria_id' => 7,
                'imagen' => 'combo-clasico-umami-productos.webp',
                'etiqueta' => 'Clásico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 21,
                'nombre' => 'Combo Mediterráneo',
                'descripcion_corta' => 'Hamburguesa Mediterránea + Papas especiadas + Agua Reishi.',
                'descripcion' => 'Hamburguesa Mediterránea + Papas especiadas + Agua Reishi. Ligero y fresco.',
                'precio' => 12800,
                'stock' => 20,
                'categoria_id' => 7,
                'imagen' => 'combo-mediterraneo-umami-productos.webp',
                'etiqueta' => 'Mediterráneo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 22,
                'nombre' => 'Combo Fungi BBQ',
                'descripcion_corta' => 'Hamburguesa Fungi BBQ + Papas & Salsas + Agua Reishi.',
                'descripcion' => 'Hamburguesa Fungi BBQ + Papas & Salsas + Agua Reishi. Intenso y ahumado.',
                'precio' => 12600,
                'stock' => 22,
                'categoria_id' => 7,
                'imagen' => 'combo-fungi-bbq-umami-productos.webp',
                'etiqueta' => 'BBQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 23,
                'nombre' => 'Combo Trufa & Shiitake',
                'descripcion_corta' => 'Hamburguesa Trufa & Shiitake + Bastones de shiitake crocantes + Agua Maitake.',
                'descripcion' => 'Hamburguesa Trufa & Shiitake + Bastones Crocantes + Agua Maitake. Gourmet y sofisticado.',
                'precio' => 13900,
                'stock' => 18,
                'categoria_id' => 7,
                'imagen' => 'combo-trufa-shiitake-umami-productos.webp',
                'etiqueta' => 'Gourmet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 24,
                'nombre' => 'Combo Spicy Gírgola',
                'descripcion_corta' => 'Hamburguesa Spicy Gírgola + Bastones de shiitake crocantes + Limonada umami.',
                'descripcion' => 'Hamburguesa Spicy Gírgola + Bastones Crocantes + Limonada UMAMI. Picante y energético.',
                'precio' => 12300,
                'stock' => 20,
                'categoria_id' => 7,
                'imagen' => 'combo-spicy-girgola-umami-productos.webp',
                'etiqueta' => 'Picante',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 25,
                'nombre' => 'Combo Wrap Saludable',
                'descripcion_corta' => 'Wrap de Hongos + Papas Rústicas + Agua Mineral.',
                'descripcion' => 'Wrap de Hongos + Papas Rústicas + Agua Mineral. Liviano y fresco.',
                'precio' => 10900,
                'stock' => 28,
                'categoria_id' => 7,
                'imagen' => 'combo-wrap-saludable-umami-productos.webp',
                'etiqueta' => 'Saludable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 26,
                'nombre' => 'Combo Nuggets Fan',
                'descripcion_corta' => 'Nuggets de Hongos + Papas & Salsas + Limonada umami.',
                'descripcion' => 'Nuggets de Hongos + Papas & Salsas + Limonada UMAMI. Divertido y crocante.',
                'precio' => 9800,
                'stock' => 30,
                'categoria_id' => 7,
                'imagen' => 'combo-nuggets-fan-umami-productos.webp',
                'etiqueta' => 'Familiar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 27,
                'nombre' => 'Combo Dúo',
                'descripcion_corta' => '2 Hamburguesas a elección + Papas XL con dips + 2 Bebidas.',
                'descripcion' => '2 Hamburguesas a elección + Papas XL + 2 bebidas. Ideal para compartir.',
                'precio' => 22500,
                'stock' => 15,
                'categoria_id' => 7,
                'imagen' => 'combo-duo-umami-productos.webp',
                'etiqueta' => 'Compartir',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'producto_id' => 28,
                'nombre' => 'Combo Wrap y Sal',
                'descripcion_corta' => 'Wrap de hongos deliciosos, condimentados con sal umami y una cerveza para acompañar. Luego de eso un brownie umami de postre.',
                'descripcion' => 'Wrap de Hongos + Sal UMAMI + Cerveza + Brownie. Completo y equilibrado.',
                'precio' => 13500,
                'stock' => 18,
                'categoria_id' => 7,
                'imagen' => 'combo-sobres-cerveza-postre-umami-productos.webp',
                'etiqueta' => 'Completo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}